twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_profile_picture_directory: 'uploads/profilePics'

when@test:
    twig:
        strict_variables: true
